### ISSUE TITLE
Ensure clean deployment

### ISSUE THREAD

**Issue by kwannoel** [Holmusk/holmusk.github.io#40]
Updates in `src` files could be missing from the main site if the `site` binary and site content are not rebuilt.

**Comment by turboMaCk** [comment]
I think it's natural for Hakyll project to have 2 independent builds. One is the build of Hakyll binary which builds Haskell source. result of this build is another compiler binary. Using this binary you compile markdown, org mode and what not to the static HTML. Having unified build that does both steps seems not that practical to me. Usually when you work on content you want to just run `site watch` and when on the generator you want to cabal/stack build the source.

The most robust approach I found is using nix as I do for my personal blog. I use a nix-shell with `site` binary https://github.com/turboMaCk/turboMaCk.github.io/blob/develop/shell.nix and when I want to work on generator I enter the `env` for the `site` derivation itself (https://github.com/turboMaCk/turboMaCk.github.io#developement-of-haskell-bin). Nix makes sure that I never enter the shell with outdated `site` binary -- the input to expression will result in different hash making sure nix builds the new derivation when entering to the shell.

With stack though you can't ensure this. there is always a possibility of running binary that doesn't match the source -- This is why pretty much everyone uses `stack build --exec foo` rather than `stack exec` all the time. Using `stack build --exec site watch` should ensure the code is build if it's outdated.

**Comment by kwannoel** [comment]
@turboMaCk Yes that is correct. The purpose of deploy.sh is for deployment however, not local development.

Also locally `stack build` does not seem to certain parts of the website in `.stack-work`. Hence I used `stack purge` to clean up. 

Let me verify what you mentioned again (maybe I'm wrong 😅).

**Comment by kwannoel** [comment]
Okay you are right @turboMaCk `stack purge` is overkill.

Running `stack build --exec site watch` gives me an error:

```
kwannoel@Kwans-MacBook-Pro holmusk.github.io % stack build --exec site watch

Error: While constructing the build plan, the following exceptions were encountered:

Unknown package: watch

Some different approaches to resolving this:


Plan construction failed.
```

But I think `stack run` does the same thing as `stack build --exec`
```
kwannoel@Kwans-MacBook-Pro holmusk.github.io % stack run --help      
Usage: stack run [-- ARGS (e.g. stack run -- file.txt)]
                 [--[no-]ghc-package-path] [--[no-]stack-exe] [--package ARG]
                 [--rts-options RTSFLAG] [--cwd DIR] [--help]
  Build and run an executable. Defaults to the first available executable if
  none is provided as the first argument.
```

The following sequence of commands worked fine for me (for development)
```
stack run site rebuild # Rebuild content
stack run site watch # Autocompile and start a preview server
```

Will update the README to use `stack run` instead and remove changes to the deployment script.

**Comment by kwannoel** [comment]
Closing this issue after what @turboMaCk has mentioned. (This wouldn't be a problem for deployment). Reopening the related issue at https://github.com/Holmusk/holmusk.github.io/issues/43

**Comment by turboMaCk** [comment]
This seems like bug in stack to me.

```
stack build --help | grep 'exec'
--exec CMD [ARGS]        Command and arguments to run after a successful build
```

but yes it seems `run` is the way to go according to documentation

```
Build and run an executable. Defaults to the first available executable if
  none is provided as the first argument.
```
